import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import { authConfigured, loadTokens, refreshTokens, signInWithPassword, type AuthTokens } from './auth'
import './App.css'

type ModuleId = 'stopwatch' | 'alarms' | 'timers' | 'world-clock'
type ViewId = 'home' | 'apis' | ModuleId
type Alarm = { id: number; hour: number; minute: number; days: number[]; name: string; enabled: boolean; timeZone: string }
type Timer = { id: string; duration: number; remaining: number; startedAt: number | null }
type City = { id: number; name: string; country: string; admin1?: string; timeZone: string }
type ClockModule = { id: ModuleId; label: string; requirements: string[]; testingApproach: string }

const notesBaseUrl = 'https://api.github.com/repos/LuisOspina/clock-notes/contents'
const defaultSoundUrl = '/sounds/default-alarm.mp3'
const alarmsApiUrl = import.meta.env.VITE_ALARMS_API_URL
const timerStorageKey = 'clock.timers'
const SwaggerUI = lazy(async () => { await import('swagger-ui-react/swagger-ui.css'); return import('swagger-ui-react') })
const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const allDays = [0, 1, 2, 3, 4, 5, 6]
const modules: ClockModule[] = [
  { id: 'stopwatch', label: 'Stopwatch', requirements: ['The initial time is 00:00.00 and only the Start button is visible.', 'Start begins the timer, changes Start to Stop, and reveals Reset and Lap.', 'Stop freezes the main timer and active lap timer, and hides Lap.', 'Start resumes a stopped timer without clearing its elapsed time or laps.', 'Reset returns the timer to 00:00.00 and clears every lap.', 'The first Lap records lap 01 and begins a live lap 02.', 'Each additional Lap freezes the active lap and begins the next one.', 'The lap list is horizontally scrollable and shows three cards at a time.'], testingApproach: 'Add your Stopwatch testing notes here as you work through them.' },
  { id: 'alarms', label: 'Alarms', requirements: ['Create up to 10 shared alarms.', 'Alarms use the saver’s local time zone and stay correct through daylight-saving changes.', 'An alarm can repeat on selected days, play the default sound, and be enabled or dismissed.', 'The app must remain open for an alarm popup and sound to occur.'], testingApproach: 'Use each alarm card’s data-alarm-id attribute for stable automation targeting.' },
  { id: 'timers', label: 'Timers', requirements: ['Timers start empty and are kept only for the current browser session.', 'Add up to five countdowns with hours, minutes, and seconds, then start, pause, reset, or delete them.', 'A finished timer plays the default alarm sound.'], testingApproach: 'Use each timer card’s data-timer-id attribute for stable automation targeting.' },
  { id: 'world-clock', label: 'World Clock', requirements: ['Always show local time and UTC.', 'Search for a city and select a result to add its local time.', 'Each city card shows its date in mm/dd/yyyy format and can be removed.'], testingApproach: 'Search results and city cards use visible city names for automation targeting.' },
]

function formatTime(milliseconds: number) { const value = Math.max(0, milliseconds); return `${String(Math.floor(value / 60_000)).padStart(2, '0')}:${String(Math.floor((value % 60_000) / 1_000)).padStart(2, '0')}.${String(Math.floor((value % 1_000) / 10)).padStart(2, '0')}` }
function formatAlarmTime(hour: number, minute: number) { return `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}` }
function getFallbackNotes(module: ClockModule) { return `# Functional requirements\n\n${module.requirements.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\n## Testing approach\n\n${module.testingApproach}` }
function getDaysText(days: number[]) { if (days.length === 7) return 'Every day'; if (days.length === 5 && [1, 2, 3, 4, 5].every((day) => days.includes(day))) return 'Weekdays'; if (days.length === 2 && days.includes(0) && days.includes(6)) return 'Weekends'; return days.slice().sort((a, b) => a - b).map((day) => dayNames[day]).join(', ') }
function currentTimeZone() { return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' }
function dateParts(date: Date, timeZone: string) { const parts = new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(date); const value = (name: string) => Number(parts.find((part) => part.type === name)?.value); return { year: value('year'), month: value('month'), day: value('day'), hour: value('hour'), minute: value('minute') } }
function zonedDate(year: number, month: number, day: number, hour: number, minute: number, timeZone: string) { const target = Date.UTC(year, month - 1, day, hour, minute); let result = new Date(target); for (let index = 0; index < 2; index += 1) { const actual = dateParts(result, timeZone); result = new Date(result.getTime() + target - Date.UTC(actual.year, actual.month - 1, actual.day, actual.hour, actual.minute)) } return result }
function nextAlarmDate(alarm: Alarm, now = new Date()) { const local = dateParts(now, alarm.timeZone); for (let offset = 0; offset < 8; offset += 1) { const sourceDate = new Date(Date.UTC(local.year, local.month - 1, local.day + offset)); if (!alarm.days.includes(sourceDate.getUTCDay())) continue; const candidate = zonedDate(sourceDate.getUTCFullYear(), sourceDate.getUTCMonth() + 1, sourceDate.getUTCDate(), alarm.hour, alarm.minute, alarm.timeZone); if (candidate > now) return candidate } return null }
function localAlarmTime(alarm: Alarm) { const next = nextAlarmDate(alarm); return next ? new Intl.DateTimeFormat(undefined, { hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(next) : formatAlarmTime(alarm.hour, alarm.minute) }
function alarmOccurrenceKey(alarm: Alarm, now = new Date()) { const clock = dateParts(now, alarm.timeZone); return `${alarm.id}-${clock.year}-${clock.month}-${clock.day}-${clock.hour}-${clock.minute}` }
function alarmIsDue(alarm: Alarm, now = new Date()) { const clock = dateParts(now, alarm.timeZone); const day = new Date(Date.UTC(clock.year, clock.month - 1, clock.day)).getUTCDay(); return alarm.enabled && alarm.days.includes(day) && alarm.hour === clock.hour && alarm.minute === clock.minute }
function nextHourTime() { const now = new Date(); return { hour: (now.getHours() + 1) % 24, minute: 0 } }

function NotesPanel({ module }: { module: ClockModule }) {
  const [notes, setNotes] = useState(() => getFallbackNotes(module))
  useEffect(() => { const controller = new AbortController(); fetch(`${notesBaseUrl}/${module.id}.md?ref=main&updated=${Date.now()}`, { cache: 'no-store', headers: { Accept: 'application/vnd.github.raw+json' }, signal: controller.signal }).then((response) => response.ok ? response.text() : Promise.reject()).then(setNotes).catch(() => {}); return () => controller.abort() }, [module])
  return <section className="requirements-panel" aria-label="Requirements and testing notes"><ReactMarkdown>{notes}</ReactMarkdown></section>
}

function AlarmDialog({ alarm, onClose, onSave, onDelete }: { alarm: Alarm | null; onClose: () => void; onSave: (alarm: Alarm) => void; onDelete?: () => void }) {
  const zone = currentTimeZone()
  const [hour, setHour] = useState(() => String(alarm?.hour ?? nextHourTime().hour).padStart(2, '0')); const [minute, setMinute] = useState(() => String(alarm?.minute ?? nextHourTime().minute).padStart(2, '0')); const [days, setDays] = useState<number[]>(alarm?.days ?? allDays); const [name, setName] = useState((alarm?.name ?? '').slice(0, 20))
  const parsedHour = Number(hour); const parsedMinute = Number(minute); const validTime = /^\d{1,2}$/.test(hour) && parsedHour >= 0 && parsedHour <= 23 && /^\d{1,2}$/.test(minute) && parsedMinute >= 0 && parsedMinute <= 59
  const save = () => { if (validTime) onSave({ id: alarm?.id ?? 0, hour: parsedHour, minute: parsedMinute, days, name: name.trim(), enabled: days.length > 0, timeZone: zone }) }
  return <div className="dialog-backdrop"><section className="alarm-dialog" role="dialog" aria-modal="true" aria-labelledby="alarm-dialog-title"><h2 id="alarm-dialog-title">{alarm ? 'Edit alarm' : 'Add alarm'}</h2><div className="form-row"><label>Time</label><div className="time-fields"><input aria-label="Hour" value={hour} inputMode="numeric" maxLength={2} placeholder="hh" onChange={(event) => setHour(event.target.value.replace(/\D/g, ''))} /><span>:</span><input aria-label="Minute" value={minute} inputMode="numeric" maxLength={2} placeholder="mm" onChange={(event) => setMinute(event.target.value.replace(/\D/g, ''))} /></div></div>{!validTime && <p className="form-warning">Use an hour from 0–23 and a minute from 0–59.</p>}<div className="form-row"><span>Days</span><div className="day-buttons" aria-label="Alarm days">{dayNames.map((day, index) => <button className={days.includes(index) ? 'selected' : ''} type="button" key={day} aria-pressed={days.includes(index)} onClick={() => setDays((current) => current.includes(index) ? current.filter((value) => value !== index) : [...current, index])}>{day[0]}</button>)}</div></div>{days.length === 0 && <p className="form-warning">No days are selected. This alarm will be disabled until you select a day.</p>}<div className="form-row"><label htmlFor="alarm-name">Name</label><input id="alarm-name" value={name} maxLength={20} placeholder="Optional" onChange={(event) => setName(event.target.value)} /></div><div className="form-row"><span>Sound</span><output>Default alarm sound</output></div><div className="form-row"><span>Saved time zone</span><output>{alarm?.timeZone ?? zone}</output></div>{alarm && alarm.timeZone !== zone && <p className="form-warning">You are editing from {zone}. Saving applies this time in your local time zone.</p>}<div className="dialog-actions">{onDelete && <button className="delete-action" type="button" onClick={onDelete}>Delete</button>}<span /><button type="button" onClick={onClose}>Cancel</button><button className="primary-action" type="button" onClick={save} disabled={!validTime}>{alarm ? 'Save' : 'Add'}</button></div></section></div>
}

function Alarms({ accessToken }: { accessToken?: string }) {
  const [alarms, setAlarms] = useState<Alarm[]>([]); const [editing, setEditing] = useState<Alarm | null | undefined>(undefined); const [ringing, setRinging] = useState<Alarm | null>(null); const [error, setError] = useState(''); const audio = useRef<HTMLAudioElement>(null); const handledOccurrences = useRef(new Set<string>()); const configurationError = alarmsApiUrl ? '' : 'Alarm API configuration is missing.'
  const request = useCallback(async (path: string, options?: RequestInit) => { const response = await fetch(`${alarmsApiUrl}${path}`, { ...options, headers: { ...(options?.body ? { 'content-type': 'application/json' } : {}), ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}) } }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(response.status === 401 ? 'Sign in to manage alarms.' : result.message || 'The alarm request failed.') }; return response.status === 204 ? undefined : response.json() }, [accessToken])
  useEffect(() => { if (!alarmsApiUrl) return; request('/alarms').then((result) => setAlarms(result.alarms)).catch((reason: Error) => setError(reason.message)) }, [request])
  const save = async (next: Alarm) => { try { setError(''); const saved: Alarm = next.id === 0 ? (await request('/alarms', { method: 'POST', body: JSON.stringify(next) })).alarm : (await request(`/alarms/${next.id}`, { method: 'PUT', body: JSON.stringify(next) })).alarm; handledOccurrences.current.add(alarmOccurrenceKey(saved)); setAlarms((current) => next.id === 0 ? [...current, saved] : current.map((alarm) => alarm.id === saved.id ? saved : alarm)); setEditing(undefined) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save alarm.') } }
  const deleteAlarm = async () => { if (!editing) return; try { await request(`/alarms/${editing.id}`, { method: 'DELETE' }); setAlarms((current) => current.filter((alarm) => alarm.id !== editing.id)); setEditing(undefined) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not delete alarm.') } }
  const dismiss = (alarm: Alarm) => { handledOccurrences.current.add(alarmOccurrenceKey(alarm)); audio.current?.pause(); setRinging(null) }
  useEffect(() => { if (ringing && audio.current) { audio.current.currentTime = 0; audio.current.play().catch(() => {}) } }, [ringing])
  useEffect(() => { const markCurrentOccurrencesHandled = () => { const currentTime = new Date(); alarms.forEach((alarm) => { if (alarmIsDue(alarm, currentTime)) handledOccurrences.current.add(alarmOccurrenceKey(alarm, currentTime)) }) }; const check = () => { const currentTime = new Date(); alarms.forEach((alarm) => { const key = alarmOccurrenceKey(alarm, currentTime); if (alarmIsDue(alarm, currentTime) && !handledOccurrences.current.has(key)) { handledOccurrences.current.add(key); setRinging(alarm) } }) }; markCurrentOccurrencesHandled(); const interval = window.setInterval(check, 1000); return () => window.clearInterval(interval) }, [alarms])
  return <section className="alarms" aria-labelledby="alarms-title"><h2 id="alarms-title">Alarms</h2><audio ref={audio} src={defaultSoundUrl} loop />{(configurationError || error) && <p className="form-warning">{configurationError || error}</p>}{alarms.length === 0 ? <p className="empty-state">No alarms yet.</p> : <div className="alarm-list">{alarms.map((alarm) => <article className="alarm-card" data-alarm-id={alarm.id} key={alarm.id} onClick={() => setEditing(alarm)}><div><p className="alarm-days">{getDaysText(alarm.days)} {alarm.name && <small>({alarm.name})</small>}</p><time>{localAlarmTime(alarm)}</time><small className="timezone-note">Saved in {alarm.timeZone}</small></div><label onClick={(event) => event.stopPropagation()}><span className="sr-only">Enable alarm {alarm.id}</span><input type="checkbox" checked={alarm.enabled} onChange={(event) => void save({ ...alarm, name: alarm.name.slice(0, 20), enabled: event.target.checked })} /></label></article>)}</div>}<button className="add-alarm" type="button" disabled={alarms.length >= 10} title={alarms.length >= 10 ? 'Maximum of 10 alarms has been reached.' : 'Add an alarm'} onClick={() => setEditing(null)}>Add alarm</button>{editing !== undefined && <AlarmDialog alarm={editing} onClose={() => setEditing(undefined)} onSave={save} onDelete={editing ? () => void deleteAlarm() : undefined} />}{ringing && <div className="dialog-backdrop"><section className="alarm-popup" role="alertdialog" aria-label="Alarm going off"><p>Alarm</p><h2>{localAlarmTime(ringing)}</h2><button className="primary-action" onClick={() => dismiss(ringing)}>Dismiss</button></section></div>}</section>
}

function Stopwatch() { const [elapsedBeforeStart, setElapsedBeforeStart] = useState(0); const [startedAt, setStartedAt] = useState<number | null>(null); const [displayElapsed, setDisplayElapsed] = useState(0); const [lapTotals, setLapTotals] = useState<number[]>([]); const lapList = useRef<HTMLDivElement>(null); const running = startedAt !== null; useEffect(() => { if (startedAt === null) return; let frame = 0; const update = () => { setDisplayElapsed(elapsedBeforeStart + performance.now() - startedAt); frame = requestAnimationFrame(update) }; frame = requestAnimationFrame(update); return () => cancelAnimationFrame(frame) }, [elapsedBeforeStart, startedAt]); const laps = lapTotals.length ? [...lapTotals, displayElapsed] : []; useEffect(() => { if (lapTotals.length) lapList.current?.scrollTo({ left: lapList.current.scrollWidth, behavior: 'smooth' }) }, [lapTotals.length]); const stop = () => { if (startedAt === null) return; const elapsed = elapsedBeforeStart + performance.now() - startedAt; setElapsedBeforeStart(elapsed); setDisplayElapsed(elapsed); setStartedAt(null) }; return <section className="stopwatch"><h2>Stopwatch</h2><output className="stopwatch-time" data-testid="stopwatch-time" role="timer">{formatTime(displayElapsed)}</output>{laps.length > 0 && <div className="lap-list" ref={lapList}>{laps.map((total, index) => <article className="lap-card" data-testid={`lap-card-${String(index + 1).padStart(2, '0')}`} key={index}><strong>{String(index + 1).padStart(2, '0')}</strong><output>{formatTime(total - (laps[index - 1] ?? 0))}</output><output>{formatTime(total)}</output></article>)}</div>}<div className="stopwatch-actions"><button className="primary-action" onClick={running ? stop : () => setStartedAt(performance.now())}>{running ? 'Stop' : 'Start'}</button>{(running || displayElapsed > 0) && <div className="secondary-actions"><button onClick={() => { setElapsedBeforeStart(0); setDisplayElapsed(0); setStartedAt(null); setLapTotals([]) }}>Reset</button>{running && <button onClick={() => setLapTotals((current) => [...current, elapsedBeforeStart + performance.now() - (startedAt ?? performance.now())])}>Lap</button>}</div>}</div></section> }

function formatCountdown(milliseconds: number) { const seconds = Math.ceil(Math.max(0, milliseconds) / 1000); return `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` }
function loadTimers() { try { const timers = JSON.parse(localStorage.getItem(timerStorageKey) ?? '[]'); return Array.isArray(timers) ? timers.filter((timer): timer is Timer => typeof timer.id === 'string' && Number.isFinite(timer.duration) && Number.isFinite(timer.remaining) && (timer.startedAt === null || Number.isFinite(timer.startedAt))) : [] } catch { return [] } }
function TimerDialog({ onClose, onAdd }: { onClose: () => void; onAdd: (duration: number) => void }) {
  const [hours, setHours] = useState(''); const [minutes, setMinutes] = useState('5'); const [seconds, setSeconds] = useState(''); const duration = (Number(hours || 0) * 3600 + Number(minutes || 0) * 60 + Number(seconds || 0)) * 1000
  const update = (setter: (value: string) => void) => (event: React.ChangeEvent<HTMLInputElement>) => setter(event.target.value.replace(/\D/g, '').slice(0, 2))
  return <div className="dialog-backdrop"><section className="alarm-dialog" role="dialog" aria-modal="true" aria-labelledby="timer-dialog-title"><h2 id="timer-dialog-title">Add timer</h2><div className="form-row"><label>Duration</label><div className="time-fields"><input aria-label="Hours" value={hours} inputMode="numeric" placeholder="hh" onChange={update(setHours)} /><span>:</span><input aria-label="Minutes" value={minutes} inputMode="numeric" placeholder="mm" onChange={update(setMinutes)} /><span>:</span><input aria-label="Seconds" value={seconds} inputMode="numeric" placeholder="ss" onChange={update(setSeconds)} /></div></div>{duration === 0 && <p className="form-warning">Set a duration greater than zero.</p>}<div className="dialog-actions"><span /><button type="button" onClick={onClose}>Cancel</button><button className="primary-action" type="button" disabled={duration === 0} onClick={() => onAdd(duration)}>Add</button></div></section></div>
}
function Timers() {
  const [timers, setTimers] = useState<Timer[]>(loadTimers); const [adding, setAdding] = useState(false); const [now, setNow] = useState(() => Date.now()); const audio = useRef<HTMLAudioElement>(null); const notified = useRef(new Set<string>()); const soundTimeout = useRef<number | null>(null)
  useEffect(() => { localStorage.setItem(timerStorageKey, JSON.stringify(timers)) }, [timers])
  useEffect(() => { const interval = window.setInterval(() => { const currentTime = Date.now(); setNow(currentTime); setTimers((current) => { const finished = current.filter((timer) => timer.startedAt && timer.remaining - (currentTime - timer.startedAt) <= 0 && !notified.current.has(timer.id)); if (finished.length && audio.current) { finished.forEach((timer) => notified.current.add(timer.id)); audio.current.currentTime = 0; audio.current.loop = true; audio.current.play().catch(() => {}); if (soundTimeout.current) window.clearTimeout(soundTimeout.current); soundTimeout.current = window.setTimeout(() => { audio.current?.pause(); if (audio.current) audio.current.currentTime = 0 }, 15_000) } return current.map((timer) => !timer.startedAt ? timer : timer.remaining - (currentTime - timer.startedAt) <= 0 ? { ...timer, remaining: 0, startedAt: null } : timer) }) }, 250); return () => window.clearInterval(interval) }, [])
  useEffect(() => () => { if (soundTimeout.current) window.clearTimeout(soundTimeout.current); audio.current?.pause() }, [])
  const add = (duration: number) => { setTimers((current) => [...current, { id: crypto.randomUUID(), duration, remaining: duration, startedAt: null }]); setAdding(false) }
  const toggle = (id: string, currentTime: number) => { setNow(currentTime); setTimers((current) => current.map((timer) => timer.id === id ? timer.startedAt ? { ...timer, remaining: Math.max(0, timer.remaining - (currentTime - timer.startedAt)), startedAt: null } : { ...timer, startedAt: currentTime } : timer)) }
  const stopAudio = () => { if (soundTimeout.current) window.clearTimeout(soundTimeout.current); audio.current?.pause(); if (audio.current) audio.current.currentTime = 0 }
  return <section className="timers" aria-labelledby="timers-title"><h2 id="timers-title">Timers</h2><audio ref={audio} src={defaultSoundUrl} /><div className="timer-list">{timers.length === 0 ? <p className="empty-state">No timers yet.</p> : timers.map((timer, index) => { const remaining = timer.startedAt ? Math.max(0, timer.remaining - Math.max(0, now - timer.startedAt)) : timer.remaining; const done = remaining === 0; return <article className={`timer-card${done ? ' timer-finished' : ''}`} aria-label={`Timer ${index + 1}`} data-testid={`timer-${timer.id}`} key={timer.id}><strong>Timer {index + 1}</strong><output role="timer">{formatCountdown(remaining)}</output>{done && <span className="sr-only" role="status">Timer finished. Reset is ready.</span>}<div><button className="primary-action" type="button" disabled={done} onClick={(event) => toggle(timer.id, performance.timeOrigin + event.timeStamp)}>{timer.startedAt ? 'Pause' : 'Start'}</button><button className="reset-action" type="button" autoFocus={done} onClick={() => { stopAudio(); notified.current.delete(timer.id); setTimers((current) => current.map((item) => item.id === timer.id ? { ...item, remaining: item.duration, startedAt: null } : item)) }}>Reset</button><button className="delete-action" type="button" aria-label={`Delete timer ${index + 1}`} onClick={() => { stopAudio(); setTimers((current) => current.filter((item) => item.id !== timer.id)) }}>Delete</button></div></article> })}</div><button className="add-alarm" type="button" disabled={timers.length >= 5} title={timers.length >= 5 ? 'Maximum of 5 timers has been reached.' : 'Add a timer'} onClick={() => setAdding(true)}>Add timer</button>{adding && <TimerDialog onClose={() => setAdding(false)} onAdd={add} />}</section>
}

function clockParts(date: Date, timeZone: string) { const display = new Intl.DateTimeFormat('en-US', { timeZone, month: '2-digit', day: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }); const parts = Object.fromEntries(display.formatToParts(date).filter((part) => part.type !== 'literal').map((part) => [part.type, part.value])); return { date: `${parts.month}/${parts.day}/${parts.year}`, time: `${parts.hour}:${parts.minute}:${parts.second}` } }
function LocationDialog({ onClose, onAdd }: { onClose: () => void; onAdd: (city: City) => Promise<void> }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<City[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const search = async (event: React.FormEvent) => { event.preventDefault(); if (!query.trim()) return; setError(''); try { const response = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query.trim())}&count=10&language=en&format=json`); const data = await response.json(); if (!response.ok) throw new Error(); setResults((data.results ?? []).filter((city: { timezone?: string }) => city.timezone).map((city: { id: number; name: string; country: string; admin1?: string; timezone: string }) => ({ id: city.id, name: city.name, country: city.country, admin1: city.admin1, timeZone: city.timezone }))) } catch { setResults([]); setError('Could not find cities right now.') } }
  const add = async (city: City) => { setSaving(true); try { await onAdd(city); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not add location.') } finally { setSaving(false) } }
  return <div className="dialog-backdrop"><section className="alarm-dialog city-dialog" role="dialog" aria-modal="true" aria-labelledby="location-dialog-title"><h2 id="location-dialog-title">Add location</h2><form className="city-search" onSubmit={search}><label htmlFor="city-query">Search city</label><div><input id="city-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search city" autoFocus /><button className="primary-action" type="submit" disabled={saving}>Search</button></div></form>{error && <p className="form-warning">{error}</p>}{results.length > 0 && <div className="city-results" aria-label="City search results">{results.map((city) => <button type="button" disabled={saving} key={city.id} onClick={() => void add(city)}><strong>{city.name}</strong><span>{[city.admin1, city.country].filter(Boolean).join(', ')}</span></button>)}</div>}<div className="dialog-actions"><span /><button type="button" onClick={onClose}>Cancel</button></div></section></div>
}
function WorldClock({ accessToken }: { accessToken?: string }) {
  const [now, setNow] = useState(() => new Date()); const [cities, setCities] = useState<City[]>([]); const [adding, setAdding] = useState(false); const [error, setError] = useState(''); const localZone = currentTimeZone()
  const request = useCallback(async (path: string, options?: RequestInit) => { const response = await fetch(`${alarmsApiUrl}${path}`, { ...options, headers: { ...(options?.body ? { 'content-type': 'application/json' } : {}), ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}) } }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(response.status === 401 || response.status === 403 ? 'Sign in to save locations.' : result.message || 'The location request failed.') }; return response.status === 204 ? undefined : response.json() }, [accessToken])
  useEffect(() => { const interval = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(interval) }, [])
  useEffect(() => { if (!alarmsApiUrl || !accessToken) return; request('/locations').then((result) => setCities(result.locations)).catch((reason: Error) => setError(reason.message)) }, [accessToken, request])
  const add = async (city: City) => { const result = await request('/locations', { method: 'POST', body: JSON.stringify(city) }); setCities((current) => current.some((item) => item.id === city.id) ? current : [...current, result.location]) }
  const remove = async (city: City) => { try { await request(`/locations/${city.id}`, { method: 'DELETE' }); setCities((current) => current.filter((item) => item.id !== city.id)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not remove location.') } }
  const fixed: City[] = [{ id: -1, name: 'Local time', country: localZone, timeZone: localZone }, { id: -2, name: 'UTC', country: 'Coordinated Universal Time', timeZone: 'UTC' }]
  const card = (city: City, removable = false) => { const clock = clockParts(now, city.timeZone); return <article className={`city-card${removable ? ' removable' : ''}`} data-testid={removable ? `location-${city.id}` : undefined} key={city.id}><div><strong>{city.name}</strong><small>{city.country}{city.admin1 ? ` · ${city.admin1}` : ''}</small></div><time dateTime={now.toISOString()}>{clock.time}</time><output>{clock.date}</output><small className="utc-offset">{new Intl.DateTimeFormat('en-US', { timeZone: city.timeZone, timeZoneName: 'shortOffset' }).formatToParts(now).find((part) => part.type === 'timeZoneName')?.value}</small>{removable && <button className="remove-city" type="button" aria-label={`Remove ${city.name}`} onClick={() => void remove(city)}>×</button>}</article> }
  return <section className="world-clock" aria-labelledby="world-clock-title"><h2 id="world-clock-title">World Clock</h2>{error && <p className="form-warning">{error}</p>}<div className="world-clock-list"><div className="world-clock-fixed">{fixed.map((city) => card(city))}</div><div className="city-list">{cities.length ? cities.map((city) => card(city, true)) : <p className="empty-state">No locations yet.</p>}</div></div><button className="add-alarm" type="button" disabled={cities.length >= 10} title={cities.length >= 10 ? 'Maximum of 10 locations has been reached.' : 'Add a location'} onClick={() => setAdding(true)}>Add location</button>{adding && <LocationDialog onClose={() => setAdding(false)} onAdd={add} />}</section>
}
function Home() { return <section className="home-panel" aria-label="Home"><div className="home-cards"><article><h2>Latest test run</h2><p>No Playwright artifacts are linked yet.</p></article></div></section> }

function ApiReference({ accessToken }: { accessToken: string }) { const openApiUrl = alarmsApiUrl ? `${alarmsApiUrl}/openapi.json` : ''; return <section className="api-reference swagger-reference" aria-labelledby="api-reference-title"><p>API documentation</p><h1 id="api-reference-title">Alarms API</h1>{openApiUrl ? <Suspense fallback={<p className="api-note">Loading API documentation…</p>}><SwaggerUI url={openApiUrl} docExpansion="list" tryItOutEnabled={false} defaultModelsExpandDepth={-1} requestInterceptor={(request) => { if (accessToken) request.headers.Authorization = `Bearer ${accessToken}`; return request }} /></Suspense> : <p className="api-note">Alarm API configuration is missing.</p>}</section> }

function ClockApp({ accessToken }: { accessToken: string }) { const [active, setActive] = useState<ViewId>('home'); const activeModule = modules.find((item) => item.id === active); return <div className="app-shell"><header className="app-header"><button className="brand" type="button" onClick={() => setActive('home')}>Clock</button><nav className="header-primary-nav" aria-label="Primary navigation"><button aria-pressed={active === 'apis'} onClick={() => setActive('apis')}>APIs</button></nav><nav className="module-nav" aria-label="Clock modules">{modules.map((item) => <button aria-pressed={active === item.id} key={item.id} onClick={() => setActive(item.id)}>{item.label}</button>)}</nav></header><main id="main" className={activeModule ? 'app-main' : 'app-main single-panel'}>{active === 'home' && <Home />}{active === 'apis' && <ApiReference accessToken="" />}{activeModule && <><NotesPanel key={activeModule.id} module={activeModule} /><section className="module-panel">{active === 'stopwatch' && <Stopwatch />}{active === 'alarms' && <Alarms accessToken={accessToken} />}{active === 'timers' && <Timers />}{active === 'world-clock' && <WorldClock accessToken={accessToken} />}</section></>}</main></div> }

function App() {
  const [tokens, setTokens] = useState<AuthTokens | null>(() => loadTokens())
  const [error, setError] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)

  useEffect(() => { if (!tokens) return; const delay = Math.max(1_000, tokens.expiresAt - Date.now() - 60_000); const timer = window.setTimeout(() => refreshTokens(tokens).then(setTokens).catch(() => setTokens(null)), delay); return () => window.clearTimeout(timer) }, [tokens])

  if (!authConfigured) return <section className="placeholder"><p>Configuration required</p><h2>Clock sign-in is not configured.</h2></section>
  if (window.location.pathname.startsWith('/sign-in')) return <section className="placeholder"><p>Clock</p><h2>Sign in</h2><form onSubmit={(event) => { event.preventDefault(); setLoading(true); setError(''); signInWithPassword(email, password).then(() => window.location.assign('/')).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }}><input aria-label="Email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" required /><input aria-label="Password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password" required /><button className="primary-action" type="submit" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button>{error && <span>{error}</span>}</form></section>
  return <ClockApp accessToken={tokens?.accessToken ?? ''} />
}
export default App
